const state={apiKey:"",missions:[],passengers:[],selectedMission:null,filter:"",wizardStep:1};
const $=(selector)=>document.querySelector(selector);
const $$=(selector)=>[...document.querySelectorAll(selector)];
const statusLabels={created:"Создана",waiting:"Запланирована",paused:"Приостановлена",processing:"Обрабатывается",running:"Запускается",searching:"Идёт поиск",option_found:"Вариант найден",reserving:"Бронирование",requires_confirmation:"Нужно подтверждение",completed:"Завершена",failed:"Ошибка",cancelled:"Отменена",expired:"Истекла"};
const eventLabels={mission_started:"Поиск запущен",search_started:"Ищем доступные варианты",options_found:"Варианты найдены",best_option_selected:"Выбран лучший вариант",reservation_started:"Начато бронирование",reservation_succeeded:"Место зарезервировано",waiting_for_user_confirmation:"Ожидается ваше подтверждение",confirmation_started:"Подтверждаем бронирование",confirmation_succeeded:"Поездка успешно оформлена",cancellation_started:"Начата отмена",cancellation_succeeded:"Бронирование отменено",mission_failed:"Не удалось выполнить поездку"};
function uid(prefix){return `web-${prefix}-${crypto.randomUUID()}`}
function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]))}
function toast(message,error=false){const node=$("#toast");node.textContent=message;node.className=`toast${error?" error":""}`;node.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.hidden=true,3500)}
async function api(path,options={}){const headers={"X-API-Key":state.apiKey,...(options.headers||{})};if(options.body)headers["Content-Type"]="application/json";const response=await fetch(path,{...options,headers});if(response.status===204)return null;const payload=await response.json().catch(()=>({}));if(!response.ok){const detail=payload.detail;throw new Error(typeof detail==="string"?detail:detail?.message||`Ошибка API: HTTP ${response.status}`)}return payload}
function initials(name){return name.split(/\s+/).map(part=>part[0]).join("").slice(0,2).toUpperCase()}
function formatDate(value){if(!value)return "—";return new Date(`${value.slice(0,10)}T00:00:00`).toLocaleDateString("ru-RU",{day:"numeric",month:"long",year:"numeric"})}
function statusBadge(status){return `<span class="status ${escapeHtml(status)}">${escapeHtml(statusLabels[status]||status)}</span>`}
function setView(name){$$('.view').forEach(view=>view.classList.toggle("active",view.id===`${name}View`||(name==="detail"&&view.id==="tripDetail")));$$('.nav').forEach(button=>button.classList.toggle("active",button.dataset.view===name));$('.sidebar').classList.remove("open")}
async function connect(){state.apiKey=$("#apiKey").value.trim();try{const readiness=await fetch("/ready").then(response=>response.json());await api("/providers");sessionStorage.setItem("purchaseAgentApiKey",state.apiKey);$("#storageText").textContent=readiness.storage_backend==="database"?"PostgreSQL подключена":"Локальное хранилище";$("#authGate").hidden=true;$("#appShell").hidden=false;await refreshAll()}catch(error){$("#authError").textContent=`Не удалось войти: ${error.message}`;$("#authError").hidden=false}}
async function refreshAll(){await Promise.all([loadMissions(),loadPassengers()])}
async function loadMissions(){try{state.missions=await api("/missions?limit=100");renderTrips()}catch(error){toast(error.message,true)}}
async function loadPassengers(){try{state.passengers=await api("/identities?limit=100");renderPassengers();renderPassengerChoices()}catch(error){toast(error.message,true)}}
function visibleMissions(){if(!state.filter)return state.missions;if(state.filter==="active")return state.missions.filter(item=>!["completed","failed","cancelled","expired"].includes(item.status));return state.missions.filter(item=>item.status===state.filter)}
function renderTrips(){const completed=state.missions.filter(item=>item.status==="completed").length;$("#totalTrips").textContent=state.missions.length;$("#actionTrips").textContent=state.missions.filter(item=>item.status==="requires_confirmation").length;$("#completedTrips").textContent=completed;const missions=visibleMissions();if(!missions.length){$("#tripList").innerHTML=`<div class="empty"><span>⌁</span><h3>${state.missions.length?"Здесь пока пусто":"Создайте первую поездку"}</h3><p>${state.missions.length?"Попробуйте другой фильтр.":"Добавьте пассажира, задайте маршрут — агент сделает остальное."}</p></div>`;return}$("#tripList").innerHTML=missions.map(mission=>`<article class="trip-card" data-mission-id="${mission.id}" tabindex="0"><div class="trip-main"><div class="trip-icon">⌁</div><div><h3>${escapeHtml(mission.payload?.origin||mission.constraints.from_city)} → ${escapeHtml(mission.payload?.destination||mission.constraints.to_city)}</h3><p>${formatDate(mission.payload?.departure_date||mission.constraints.travel_date)} · ${mission.participant_ids.length} пассажир</p></div></div><div class="trip-side">${statusBadge(mission.status)}<small>${escapeHtml(mission.resolved_provider_id||mission.provider_id||"mock_train")}</small></div></article>`).join("");$$('.trip-card').forEach(card=>{card.addEventListener("click",()=>openMission(card.dataset.missionId));card.addEventListener("keydown",event=>{if(event.key==="Enter")openMission(card.dataset.missionId)})})}
function renderPassengers(){if(!state.passengers.length){$("#passengerList").innerHTML='<div class="empty"><span>◎</span><h3>Нет пассажиров</h3><p>Добавьте профиль, чтобы использовать его в поездках.</p></div>';return}$("#passengerList").innerHTML=state.passengers.map(person=>`<article class="passenger-card"><div class="avatar">${escapeHtml(initials(person.display_name))}</div><h3>${escapeHtml(person.display_name)}</h3><p>${formatDate(person.birth_date)}</p><p>${person.documents.length?`Документов: ${person.documents.length}`:"Без документа"}</p><footer>ID · ${person.id.slice(0,8)}</footer></article>`).join("")}
function renderPassengerChoices(){const target=$("#passengerChoices");if(!target)return;if(!state.passengers.length){target.innerHTML='<div class="empty"><h3>Сначала добавьте пассажира</h3><p>Закройте окно и откройте раздел «Пассажиры».</p></div>';return}target.innerHTML=state.passengers.map((person,index)=>`<label class="choice"><input type="checkbox" name="passenger" value="${person.id}" ${index===0?"checked":""}><span class="avatar">${escapeHtml(initials(person.display_name))}</span><span><b>${escapeHtml(person.display_name)}</b><small>${formatDate(person.birth_date)}</small></span></label>`).join("")}
async function openMission(id){try{state.selectedMission=await api(`/missions/${id}`);renderMissionDetail();setView("detail");await loadActivity(id)}catch(error){toast(error.message,true)}}
function missionActions(mission){const actions=[];if(["created","waiting"].includes(mission.status))actions.push('<button class="primary mission-action" data-action="run">Запустить поиск</button>');if(mission.status==="requires_confirmation")actions.push('<button class="primary mission-action" data-action="confirm">Подтвердить</button>');if(!["completed","cancelled","expired"].includes(mission.status))actions.push('<button class="secondary mission-action" data-action="cancel">Отменить</button>');if(mission.status==="failed")actions.push('<button class="primary mission-action" data-action="retry">Повторить</button>');return actions.join("")}
function renderMissionDetail(){const mission=state.selectedMission,option=mission.best_option||{},route=`${mission.payload?.origin||mission.constraints.from_city} → ${mission.payload?.destination||mission.constraints.to_city}`;const price=option.price?.amount??option.price;$("#tripDetailContent").innerHTML=`<section class="detail-hero"><div><p class="eyebrow">ПОЕЗДКА · ${mission.id.slice(0,8)}</p><h2>${escapeHtml(route)}</h2><p>${formatDate(mission.payload?.departure_date||mission.constraints.travel_date)} · ${statusLabels[mission.status]||mission.status}</p></div><div class="detail-actions">${missionActions(mission)}</div></section><div class="detail-grid"><article class="detail-card"><h3>Детали поездки</h3><div class="facts"><div class="fact"><small>Статус</small>${statusBadge(mission.status)}</div><div class="fact"><small>Пассажиры</small><b>${mission.participant_ids.length}</b></div><div class="fact"><small>Провайдер</small><b>${escapeHtml(mission.resolved_provider_id||mission.provider_id||mission.provider)}</b></div><div class="fact"><small>Режим</small><b>${mission.execution_mode==="auto_purchase"?"Автоматически":mission.execution_mode==="search_only"?"Только поиск":"С подтверждением"}</b></div><div class="fact"><small>Поезд</small><b>${escapeHtml(option.train_number||"Пока не выбран")}</b></div><div class="fact"><small>Цена</small><b>${price?`${price} ${option.price?.currency||"RUB"}`:"Пока неизвестна"}</b></div></div></article><article class="detail-card"><h3>Что дальше?</h3><p class="muted">${nextActionText(mission.status)}</p><details><summary>Технические данные</summary><pre>${escapeHtml(JSON.stringify(mission,null,2))}</pre></details></article></div>`;$$('.mission-action').forEach(button=>button.addEventListener("click",()=>performMissionAction(button.dataset.action)))}
function nextActionText(status){return {created:"Запустите поиск — агент подберёт и зарезервирует лучший вариант.",waiting:"Миссия ожидает назначенного времени запуска.",requires_confirmation:"Вариант зарезервирован. Подтвердите его, чтобы завершить оформление.",completed:"Поездка успешно оформлена. Дополнительных действий не требуется.",failed:"Произошла ошибка. Можно повторить попытку.",cancelled:"Поездка отменена.",expired:"Срок выполнения поездки истёк."}[status]||"Агент выполняет текущий этап. Обновите страницу через несколько секунд."}
async function performMissionAction(action){const mission=state.selectedMission;try{let path=`/missions/${mission.id}/${action}`;let body;if(action==="retry")body=JSON.stringify({});state.selectedMission=await api(path,{method:"POST",headers:{"Idempotency-Key":uid(action)},body});toast(action==="confirm"?"Бронирование подтверждено":action==="cancel"?"Поездка отменена":"Действие выполнено");renderMissionDetail();await loadMissions();await loadActivity(mission.id)}catch(error){toast(error.message,true)}}
async function loadActivity(id){try{const result=await api(`/missions/${id}/events?limit=100`);const items=result.items||[];$("#activityEmpty").hidden=items.length>0;$("#activityList").innerHTML=items.map(item=>`<article class="event"><b>${escapeHtml(eventLabels[item.event?.type||item.type]||item.event?.type||item.type||"Событие")}</b><small>${item.event?.occurred_at||item.occurred_at?new Date(item.event?.occurred_at||item.occurred_at).toLocaleString("ru-RU"):""}</small></article>`).join("")}catch(error){$("#activityList").innerHTML=`<div class="error">${escapeHtml(error.message)}</div>`}}
function setWizardStep(step){state.wizardStep=step;$$('.wizard-step').forEach(node=>node.classList.toggle("active",Number(node.dataset.wizard)===step));$$('.progress i').forEach((node,index)=>node.classList.toggle("active",index<step));if(step===3)renderReview()}
function selectedPassengers(){return $$('input[name="passenger"]:checked').map(input=>input.value)}
function renderReview(){const names=selectedPassengers().map(id=>state.passengers.find(person=>person.id===id)?.display_name).filter(Boolean);$("#tripReview").innerHTML=`<div class="review-row"><span>Маршрут</span><b>${escapeHtml($("#origin").value)} → ${escapeHtml($("#destination").value)}</b></div><div class="review-row"><span>Дата</span><b>${formatDate($("#travelDate").value)}</b></div><div class="review-row"><span>Пассажиры</span><b>${escapeHtml(names.join(", "))}</b></div><div class="review-row"><span>Провайдер</span><b>Mock Train</b></div>`}
async function createTrip(event){event.preventDefault();const passengers=selectedPassengers();if(!passengers.length){toast("Выберите хотя бы одного пассажира",true);setWizardStep(2);return}const button=event.submitter;button.disabled=true;const origin=$("#origin").value.trim(),destination=$("#destination").value.trim(),date=$("#travelDate").value;try{let mission=await api("/missions",{method:"POST",headers:{"Idempotency-Key":uid("mission")},body:JSON.stringify({type:"train_trip",title:`${origin} — ${destination}`,participant_ids:passengers,provider:"mock_train",provider_id:"mock_train",execution_mode:$("#executionMode").value,payload:{origin,destination,departure_date:date},constraints:{from_city:origin,to_city:destination,travel_date:date,passengers_count:passengers.length}})});mission=await api(`/missions/${mission.id}/run`,{method:"POST",headers:{"Idempotency-Key":uid("run")}});$("#tripDialog").close();state.selectedMission=mission;await loadMissions();renderMissionDetail();setView("detail");await loadActivity(mission.id);toast("Поездка создана, лучший вариант найден")}catch(error){toast(error.message,true)}finally{button.disabled=false}}
async function createPassenger(event){event.preventDefault();const button=event.submitter;button.disabled=true;const type=$("#documentType").value,number=$("#documentNumber").value.trim();if(type&&!number){toast("Укажите номер документа",true);button.disabled=false;return}try{const first=$("#firstName").value.trim(),last=$("#lastName").value.trim();await api("/identities",{method:"POST",headers:{"Idempotency-Key":uid("identity")},body:JSON.stringify({display_name:`${first} ${last}`,first_name:first,last_name:last,birth_date:$("#birthDate").value,documents:type?[{type,number}]:[]})});$("#passengerDialog").close();event.target.reset();await loadPassengers();toast("Пассажир добавлен")}catch(error){toast(error.message,true)}finally{button.disabled=false}}
$("#authForm").addEventListener("submit",event=>{event.preventDefault();connect()});$("#logout").addEventListener("click",()=>{sessionStorage.removeItem("purchaseAgentApiKey");location.reload()});$$('.nav').forEach(button=>button.addEventListener("click",()=>{setView(button.dataset.view);if(button.dataset.view==="activity"&&state.selectedMission)loadActivity(state.selectedMission.id)}));$("#mobileMenu").addEventListener("click",()=>$('.sidebar').classList.toggle("open"));$$('[data-view-target]').forEach(button=>button.addEventListener("click",()=>setView(button.dataset.viewTarget)));$("#newTrip").addEventListener("click",()=>{if(!state.passengers.length){toast("Сначала добавьте пассажира",true);setView("passengers");return}setWizardStep(1);$("#tripDialog").showModal()});$("#newPassenger").addEventListener("click",()=>$("#passengerDialog").showModal());$("#passengerForm").addEventListener("submit",createPassenger);$("#tripForm").addEventListener("submit",createTrip);$$('.next').forEach(button=>button.addEventListener("click",()=>{if(state.wizardStep===1&&!$("#tripForm").reportValidity())return;if(state.wizardStep===2&&!selectedPassengers().length){toast("Выберите пассажира",true);return}setWizardStep(state.wizardStep+1)}));$$('.previous').forEach(button=>button.addEventListener("click",()=>setWizardStep(state.wizardStep-1)));$$('.filter').forEach(button=>button.addEventListener("click",()=>{$$('.filter').forEach(item=>item.classList.remove("active"));button.classList.add("active");state.filter=button.dataset.status;renderTrips()}));$("#refreshTrips").addEventListener("click",loadMissions);
const saved=sessionStorage.getItem("purchaseAgentApiKey");if(saved)$("#apiKey").value=saved;const date=new Date();date.setDate(date.getDate()+30);$("#travelDate").value=date.toISOString().slice(0,10);if(saved)connect();
